twig:
    file_name_pattern: "*.twig"
    form_themes: ["form/default.html.twig"]

    globals:
        APP_DOMAIN: "%env(APP_DOMAIN)%"
        APP_NAME: "%env(APP_NAME)%"

        PROJECT_NAME: "%env(PROJECT_NAME)%"
        PROJECT_HEADLINE: "%env(PROJECT_HEADLINE)%"
        PROJECT_DESCRIPTION: "%env(PROJECT_DESCRIPTION)%"
        PROJECT_PRIMARY_COLOR: "%env(PROJECT_PRIMARY_COLOR)%"
        PROJECT_SECONDARY_COLOR: "%env(PROJECT_SECONDARY_COLOR)%"

        CUSTOMER_NAME: "%env(CUSTOMER_NAME)%"
        CUSTOMER_DESCRIPTION: "%env(CUSTOMER_DESCRIPTION)%"

        MAILER_NAME: "%env(MAILER_NAME)%"
        MAILER_DOMAIN: "%env(MAILER_DOMAIN)%"
when@test:
    twig:
        strict_variables: true
